### ISSUE TITLE
Wasabi be killed

### ISSUE THREAD

**Issue by LanceXJH** [danleh/wasabi#15]
I tried to use wasabi to analyze opencv.js but it was killed everytime I implemented it to opencv_js.wasm:
`$wasabi opencv_js.wasm 
`
and the result goes:
`Killed`

Is it because this opencv_js.wasm is too large(5.4MB)?

**Comment by danleh** [comment]
Hi :-)
Some more info would be great: which OS, did you compile wasabi yourself, can you run with `RUST_BACKTRACE=1` to get more error information.
`Killed` is not an error message that Wasabi usually outputs, so I am not sure where this is coming from. Is some security or resource policy killing the process? Can you observer CPU/memory consumption?

I don't think 5.4MB is too large. For reference: I instrumented the unreal engine 4 binary (which is ~20MB) on a laptop with 16GB of RAM.

**Comment by danleh** [comment]
Closing this due to missing additional information. Please comment & re-open if it's still an issue.
