### ISSUE TITLE
How can I get code coverage information from the Wasabi after getting the instrumented wasm.

### ISSUE THREAD

**Issue by tareq97** [danleh/wasabi#26]

**Comment by danleh** [comment]
Hi Tareq,
please see http://wasabi.software-lab.org/#how-does-it-work for a quick overview. In short, the process is:

1. Compile Wasabi, run it on a wasm file to obtain instrumented wasm (what you already have).
2. Replace the original wasm file with the instrumented one, add generated *.wasabi.js file to html file, which loads the wasm.
3. Write or use one of the coverage analyses from https://github.com/danleh/wasabi/tree/master/analyses, also add to the html file.
4. Open html site in browser to run the wasm file + analysis.
5. In case you use the coverage analysis from above, check the console for output.

General notes:
- Wasabi currently only supports Wasm in browsers, Node.js is TODO.
- The coverage will be given in terms of Wasm functions and instructions, NOT in terms of the source language (e.g., C++ or Rust). 
- To obtain coverage in the source language, one would have to map bytecode instructions back to source lines with the help of some debug info (DWARF, source maps). Nothing of that is implemented yet.

If you would like more concrete help, you should post a minimal (non-)working example and a detailed description what you tried so far.

**Comment by tareq97** [comment]
Thanks for the reply @danleh,

I have gone through the analyses examples and also the looked at the Tutorial at PLDI 2019 which were really helpful. Using that information,
1. I have taken the Rosetta C example converted it to wasm file using emscripten using below command.
```
emcc -s WASM=1 -s EXPORTED_FUNCTIONS='["_main","_agm"]' -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap","ccall"]'  Arithmetic-geometric_mean.c -s FORCE_FILESYSTEM=1 -s NO_EXIT_RUNTIME=1 -s ALLOW_MEMORY_GROWTH=1 -o agm.html
```
2. Then instrumented that wasm file previously generated from emscripten with wasabi. This step result in a instrumented wasm file and js file containing all the hooks information got generated in out folder.
3. Then created "agm_analysis.js" apart from the other two files which got generated through wasabi. This file contains the same code as that of "coverage-instruction.js" given in the link  https://github.com/danleh/wasabi/tree/master/analyses. Also printed the coverage in the console using console.log(Please find the attached screenshot of the console output.)
4. Linked all the above-mentioned files in the HTML file and call the function present in wasm file called "agm"(the agm method is exported as shown in the previous command of emcc in step 1)  using the below code in HTML file.
```
Module.onRuntimeInitialized = _ => {
        //let input = window.prompt("What is the password?");
        let result = Module.cwrap('agm', 'number', ["number","number"]);
        var r = result(1.0,2.0);
	console.log(r);
      };
```

**Doubt:** 
I was not able to understand what coverage information is being printed in the console log. But I am able to see an array of length 107 being printed when printing console.log(Wasabi.analysisResult).
Is it the number of instruction covered in wasm file when we run the wasm function using emscripten exported method Module.cwrap in the html file function or the total list of instructions present in the wasm file. 
Actually, when I am referring to code coverage I am referring to wasm file coverage not the source file coverage. I was hoping that "coverage-instruction.js" gives me the coverage of wasm file, not the source program in C or C++ or rust. Need more information on the output of Wasabi.analysisResult in the shared sample files.  

Kindly run the shared HTML file and see the output Array being printed in the console log.

**Prerequisite:** 
1. Run this HTML file using the simple local server using below command
```
python -m SimpleHTTPServer 8000
```
2. When the HTML is launched it will expect two input double types as per the Rosetta C program example. Please give input as 1.0 and 2.0 and enter 2 times then cancel the prompt and see the output in devtools console using files attached
[agm.zip](https://github.com/danleh/wasabi/files/4412067/agm.zip)
.
**Screenshot:**
![wasabi_analysisresult](https://user-images.githubusercontent.com/10094302/78086436-39449d80-73be-11ea-8995-33d8b0dfe28f.png)

**Comment by monperrus** [comment]
Thanks @tareq97 and @danleh!

@danleh Have you ever heard of a coverage tool for WASM (not necessarily implemented on top of Wasabi)?

**Comment by danleh** [comment]
> @danleh Have you ever heard of a coverage tool for WASM (not necessarily implemented on top of Wasabi)?

No, I haven't heard of anything. 

But I just google'd out of interest and found this blog post: https://motley-coder.com/2019/03/31/webassembly-coverage/ (Some restrictions however: it seems very early and prototype-ish, you need to modify LLVM/compiler-rt and it only works for Clang or Emscripten using the more recent "upstream" backend, not other producers of Wasm.)

**Comment by danleh** [comment]
@tareq97 Thanks a lot for the detailed report and minimal example! That was great for helping me understand the issue :+1:. I believe you are already there 95% of the way. As for your questions:

- The analysis you used implements very simple "instruction coverage" (there are other types of coverage as well, e.g., branch coverage). For each instruction, it stores a bool whether the instruction was executed or not.
- An instruction in that analysis is identified by two numbers: the function index in the WebAssembly binary, i.e., a number from 0 to #function count (see Wasm spec for more info: https://webassembly.github.io/spec/core/text/modules.html#indices) and the index of the instruction inside that function. I.e., instruction `[3, 5]` would be the 6th instruction (starting to count at 0) in function with index 3.
- The `coverage` variable in the analysis is a two-dimensional array, where the first dimension is the function index and the second is the instruction index. The values are bools (i.e., true if the instruction was executed, false if not).

**Comment by danleh** [comment]
Since there hasn't been any followup question/activity, I close this for now. Reopen/comment if you wish.

**Comment by monperrus** [comment]
For the record, we're looking into getting the instruction coverage of a WASM module using an interpreter (https://github.com/satabin/swam/)

**Comment by danleh** [comment]
That's great to hear and a cool project!

Let me know if I can explain or help with smaller things, also via email. (Since I am mostly on my own, implementing larger new features are probably unrealistic.)
