### ISSUE TITLE
Is Wasabi.analysis.memory implemented?

### ISSUE THREAD

**Issue by yihan0512** [danleh/wasabi#28]
Hello,

I instrumented my code with Wasabi and run, I got the following error:

`Uncaught TypeError: Cannot read property 'size' of undefined`
    `at memory.size (main.wasabi.js:577)`
    `at <anonymous>:wasm-function[495]:0x52dbf`
    `at malloc (<anonymous>:wasm-function[493]:0x43f4c)`
    `at <anonymous>:wasm-function[379]:0x1690b`
    `at send (<anonymous>:wasm-function[168]:0x2438)`
    `at main.js:1730`
    `at Object.ccall (main.js:751)`
    `at <anonymous>:1:8`

This is because Wasabi.analysis.memory is undefined,  so my question is, is Wasabi.analysis.memory implemented anywhere in wasabi.js or I have to implement it by myself? I did not see any example in analyses/ defining memory as well.

**Comment by danleh** [comment]
Could you upload your WebAssembly file (or a simplified example) and the generated JS file by Wasabi that gives you troubles? Then I can give more concrete help/debugging.

Some quick ideas/starting points:
- Yes, support for the `memory.grow` and `memory.size` instructions should be implemented in Wasabi.
- The instructions were renamed (from `memory_grow` and `memory_size` originally) in the Wasm spec, after Wasabi was released, and I tried to align it again to the spec, maybe I did an error there.
- See the log_all analysis for a "template" with all available hooks: https://github.com/danleh/wasabi/blob/master/analyses/log-all.js, does this also produce the error for you?
- Are you using the most recent master branch of Wasabi or some older version?

If there is a bug, then I believe it would be in https://github.com/danleh/wasabi/blob/master/src/instrument/add_hooks/hook_map.rs#L380
Could you try adding a `.replace('.', '_')` to that line, recompile Wasabi, and see if that fixes it?

**Comment by yihan0512** [comment]
Thank you for your reply. I think it is because in the two lines below (copied from a generated wasabi.js file):

`    "memory.grow": function (func, instr, deltaPages, previousSizePages) {
        Wasabi.analysis.memory.grow({func, instr}, deltaPages, previousSizePages);
    }`
    `"memory.size": function (func, instr, currentSizePages) {
        Wasabi.analysis.memory.size({func, instr}, currentSizePages);
    }`

JavaScript treated Wasabi.analysis.memory as an object and grow/size being it's methods. I  replace the two `.` with `_` and the problem is fixed. 

`    "memory.grow": function (func, instr, deltaPages, previousSizePages) {
        Wasabi.analysis.memory_grow({func, instr}, deltaPages, previousSizePages);
    }`
    `"memory.size": function (func, instr, currentSizePages) {
        Wasabi.analysis.memory_size({func, instr}, currentSizePages);
    }`

I also tried to follow your instructions to modify hook_map.rs by adding `.replace('.', '_')` but cannot compile.

`error[E0308]: mismatched types`
  ` --> src/instrument/add_hooks/hook_map.rs:380:53`
   ` |`
`380 |     let mut mangled = name.to_string().replace('.', '_');`
   ` |                                                     ^^^ expected \`&str\`, found \`char\`\``

**Comment by danleh** [comment]
should be fixed now in master, let me know if you still have troubles (then I will reopen again)
