### ISSUE TITLE
enumset causing wasabi to not be compilable

### ISSUE THREAD

**Issue by arctumn** [danleh/wasabi#30]
![image](https://user-images.githubusercontent.com/10279395/107509460-837bdb00-6b9a-11eb-8382-ad283d1ce6a8.png)
Solution update enumset to version 1.0.4 in cargo.toml

enumset = "1.0.4"

**Comment by danleh** [comment]
Thanks a lot for the report!
Testing quickly, should be merged in a little bit...

**Comment by danleh** [comment]
Done, should compile again with Rust stable/beta/nightly :-)
