### ISSUE TITLE
local count too large after instrumentation

### ISSUE THREAD

**Issue by orchestrah** [danleh/wasabi#46]
Hi ! 

I ve instrumented wasm and then trying to test it without any analysis script. 
But getting following error in Chrome console:

CompileError: WebAssembly.instantiate(): Compiling function #687 failed: local count too large @+4757612 

According to this:  https://github.com/MIPS/external-v8/blob/master/src/wasm/wasm-limits.h
There is a limit for function locals equal to 50 000 ? 

Any workaround on this ?  Is it possible to increase this limit without rebuilding Chrome ? 
Maybe Wasabi inserting too many locals in some way ?

**Comment by doehyunbaek** [comment]
Yeah it is a known problem that Wasabi's insertion of local variables while instrumentaing can exceed the maximum local count. Refer to this issue https://github.com/danleh/wasabi/issues/42

I have a fork that alleviates this problem to some degree, if you want to try, here is the link:

https://github.com/jakobgetz/wasabi/tree/jakob

**Comment by orchestrah** [comment]
> Yeah it is a known problem that Wasabi's insertion of local variables while instrumentaing can exceed the maximum local count. Refer to this issue #42
> 
> I have a fork that alleviates this problem to some degree, if you want to try, here is the link:
> 
> https://github.com/jakobgetz/wasabi/tree/jakob

Tnaks a lot fot quick reply. I ll give it a try today

**Comment by orchestrah** [comment]
Dublicate of https://github.com/danleh/wasabi/issues/42
