### ISSUE TITLE
Unity Games

### ISSUE THREAD

**Issue by Nucito** [danleh/wasabi#47]
Its possible to use this with unity games? already have tried but give a lot many errors

**Comment by danleh** [comment]
I am not aware of any fundamental reason why instrumentation for Unity Wasm binaries could be different than for other Wasm binaries. Unfortunately, your error description is pretty vague, so I have a hard time following up on this. In the future please give more details, e.g.: which game, which binary, what is the exact error message, what have you tried so far, browser, operating system, does the binary use any Wasm extensions, etc.
